Projekt_Jordnaer/Pages/Medlemmer/CreateMember.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Projekt_Jordnaer.Interfaces;
using Projekt_Jordnaer.Models;
using System.Drawing;

namespace Projekt_Jordnaer.Pages.Medlemmer
{
    public class CreateMemberModel : PageModel
    {
        [BindProperty]
        
        public Medlem Medlem { get; set; }

        private IMedlemService mservice;

        public CreateMemberModel(IMedlemService medlemService)
        {
            mservice = medlemService;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            await mservice.CreateMemberAsync(Medlem);
            return RedirectToPage("GetAllMembers");
        }

        public async Task<IActionResult> OnPostCancel()
        {
            return RedirectToPage("GetAllMembers");
        }
    }
}

Projekt_Jordnaer/Pages/Medlemmer/DeleteMember.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Projekt_Jordnaer.Interfaces;
using Projekt_Jordnaer.Models;
using System.Diagnostics.Metrics;
using System.Drawing;

namespace Projekt_Jordnaer.Pages.Medlemmer
{
    public class DeleteMemberModel : PageModel
    {
        [BindProperty]

        public Medlem MemberToDelete { get; set; }

        private IMedlemService _mService { get; set; }

        public DeleteMemberModel(IMedlemService mService)
        {
                _mService = mService;
        }

        public async Task OnGetAsync(int memberID)
        {
            MemberToDelete = await _mService.GetMemberFromIDAsync(memberID); 
        }

        public async Task<IActionResult> OnPostAsync(int memberID)
        {
            await _mService.DeleteMemberAsync(memberID);
            return RedirectToPage("GetAllMembers");
        }

        public async Task<IActionResult> OnPostCancel(int memberID)
        {
              return RedirectToPage("GetAllMembers");
        }
    }
}

Projekt_Jordnaer/Pages/Medlemmer/GetAllMembers.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Microsoft.IdentityModel.Tokens;
using Projekt_Jordnaer.Interfaces;
using Projekt_Jordnaer.Models;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Projekt_Jordnaer.Pages.Medlemmer
{
    public class GetAllMembersModel : PageModel
    {
            [BindProperty]

            public List<Medlem> Medlemmer { get; set; }

            private IMedlemService mService;

            public GetAllMembersModel(IMedlemService medlemService)
            {
                mService = medlemService;
            }

            public async Task OnGetAsync()
            {
                    Medlemmer = await mService.GetAllMembersAsync();
            }

            public async Task <IActionResult> OnPostOpret()
            {
                return RedirectToPage("CreateMember");
            }
    }
}

Projekt_Jordnaer/Pages/Medlemmer/UpdateMember.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Projekt_Jordnaer.Interfaces;
using Projekt_Jordnaer.Models;
using System.Drawing;

namespace Projekt_Jordnaer.Pages.Medlemmer
{
    public class UpdateMemberModel : PageModel
    {
        [BindProperty]

        public Medlem MemberToUpdate { get; set; }

        private IMedlemService _mService;

        public UpdateMemberModel(IMedlemService mService)
        {
            _mService = mService;
        }

        public async Task OnGet(int memberID)
        {
            MemberToUpdate = await _mService.GetMemberFromIDAsync(memberID);
        }

        public async Task<IActionResult> OnPost()
        {
            bool ok = await _mService.UpdateMemberAsync(MemberToUpdate, MemberToUpdate.MemberID);
            if (ok == true)
            {
                return RedirectToPage("GetAllMembers");
            }
            else
            {
                return Page();
            }
        }

        public async Task<IActionResult> OnPostCancel()
        {
            return RedirectToPage("GetAllMembers");
        }
    }
}

Projekt_Jordnaer/Pages/Medlemmer/CreateMember.cshtml
@page
@model Projekt_Jordnaer.Pages.Medlemmer.CreateMemberModel
@{
    ViewData["Title"] = "Opret medlem";
}

<h1>Opret medlem</h1>

<h3>Her kan du oprette et medlem</h3>
<h4>Skriv alle oplysninger nedenunder</h4>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Medlem.Name" class="control-label"></label>
                <input asp-for="@Model.Medlem.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Medlem.Address" class="control-label"></label>
                <input asp-for="@Model.Medlem.Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Medlem.Email" class="control-label"></label>
                <input asp-for="@Model.Medlem.Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Medlem.PhoneNr" class="control-label"></label>
                <input asp-for="@Model.Medlem.PhoneNr" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Medlem.Certificate" class="control-label"></label>
                <input type="checkbox" asp-for ="@Model.Medlem.Certificate" value="true" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Medlem.Admin" class="control-label"></label>
                <input type="checkbox" asp-for="@Model.Medlem.Admin" value="true" />
            </div>
            <div class="form-group">
                <input type="submit" value="Opret" class="btn btn-primary" style="background-color: green" />
            </div>
            <div class="form-group">
                <input type="submit" value="Annuller" asp-page-handler="Cancel" class="btn btn-primary" style="background-color: red" />
            </div>
        </form>
    </div>
</div>

Projekt_Jordnaer/Pages/Medlemmer/DeleteMember.cshtml
@page
@model Projekt_Jordnaer.Pages.Medlemmer.DeleteMemberModel
@{
    ViewData["Title"] = "Slet medlem";
}

<h1>Slet medlem</h1>

<h3>Her kan du slette et medlem</h3>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.MemberToDelete.MemberID" class="control-label"></label>
                <input asp-for="@Model.MemberToDelete.MemberID" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToDelete.Name" class="control-label"></label>
                <input asp-for="@Model.MemberToDelete.Name" class="form-control" disabled/>
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToDelete.Address" class="control-label"></label>
                <input asp-for="@Model.MemberToDelete.Address" class="form-control" disabled/>
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToDelete.Email" class="control-label"></label>
                <input asp-for="@Model.MemberToDelete.Email" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToDelete.PhoneNr" class="control-label"></label>
                <input asp-for="@Model.MemberToDelete.PhoneNr" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToDelete.Certificate" class="control-label"></label>
                <input type="checkbox" asp-for="@Model.MemberToDelete.Certificate" value="false" disabled />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToDelete.Admin" class="control-label"></label>
                <input type="checkbox" asp-for="@Model.MemberToDelete.Admin" value="false" disabled />
            </div>
            <div class="form-group">
                <input type="submit" value="Slet medlem" class="btn btn-primary" style="background-color: green" />
            </div>
            <div class="form-group">
                <input type="submit" value="Annuller" asp-page-handler="Cancel" class="btn btn-primary" style="background-color: red" />
            </div>
        </form>
    </div>
</div>

Projekt_Jordnaer/Pages/Medlemmer/GetAllMembers.cshtml
@page
@model Projekt_Jordnaer.Pages.Medlemmer.GetAllMembersModel
@{
    ViewData["Title"] = "Oversigt over medlemmer";
}
<h1>Oversigt over medlemmer</h1>

<form method="post">
    <div class="form-group">
        <input type="submit" value="Opret nyt medlem" asp-page-handler="Opret" class="btn btn-primary" style="background-color: green" />
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Medlem ID
            </th>
            <th>
                Navn
            </th>
            <th>
                Adresse
            </th>
            <th>
                Email
            </th>
            <th>
                Telefon nr.
            </th>
            <th>
                Certifikat
            </th>
            <th>
                Admin
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Medlemmer.Count() != 0)
        {
            @foreach (var item in Model.Medlemmer)
            {
                <tr>
                    <td>
                        @item.MemberID
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Address
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.PhoneNr
                    </td>
                    <td>
                        @item.Certificate
                    </td>
                    <td>
                        @item.Admin
                    </td>
                    <td>
                        <a asp-page="DeleteMember" asp-route-MemberID="@item.MemberID">Slet</a>|
                        <a asp-page="UpdateMember" asp-route-MemberID="@item.MemberID">Redigér</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Projekt_Jordnaer/Pages/Medlemmer/UpdateMember.cshtml
@page
@model Projekt_Jordnaer.Pages.Medlemmer.UpdateMemberModel
@{
    ViewData["Title"] = "Redigér medlem";
}

<h1>Redigér medlem</h1>

<h3>Her kan du redigére oplysningerne for et medlem</h3>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <input asp-for="@Model.MemberToUpdate.MemberID" hidden class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToUpdate.Name" class="control-label"></label>
                <input asp-for="@Model.MemberToUpdate.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToUpdate.Address" class="control-label"></label>
                <input asp-for="@Model.MemberToUpdate.Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToUpdate.Email" class="control-label"></label>
                <input asp-for="@Model.MemberToUpdate.Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToUpdate.PhoneNr" class="control-label"></label>
                <input asp-for="@Model.MemberToUpdate.PhoneNr" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToUpdate.Certificate" class="control-label"></label>
                <input type="checkbox" asp-for="@Model.MemberToUpdate.Certificate" value="true" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MemberToUpdate.Admin" class="control-label"></label>
                <input type="checkbox" asp-for="@Model.MemberToUpdate.Admin" value="true" />
            </div>
            <div class="form-group">
                <input type="submit" value="Opdater" class="btn btn-primary" style="background-color: green" />
            </div>
            <div class="form-group">
                <input type="submit" value="Annuller" asp-page-handler="Cancel" class="btn btn-primary" style="background-color: red" />
            </div>
        </form>
    </div>
</div>